export const API_CONFIG = {
  AUTH_URL: "https://authsvc2.alpa.org/api/token/auth",
  FLIGHT_INFO_URL: "https://gateway.alpa.org/api/FlightSearchV2/FindFlightsInfo",
  SEARCH_URL: "https://gateway.alpa.org/api/FlightSearchV2/SearchFlights",
  CACHE_DURATION_MS: 1000 * 60 * 30, // 30 minutes
};

export const DEFAULT_SEARCH_PARAMS = {
  isNonStopSearch: true,
  isOneStopSearch: false,
  isTwoStopSearch: false,
  arriveBy: "1970-01-01 23:59:59",
  avoidConnectionAirportCodes: [] as string[],
  requireConnectionAirportCodes: [] as string[],
  minConnectionTime: 30,
  maxTotalTravelTime: 2880,
  isCargoIncluded: true,
  isRegionalIncluded: true,
  page: 1,
  pageSize: 30,
  sortBy: 0,
  isSortDesc: false,
  lighteningMode: true,
  requiredAircrafts: [] as string[],
  requiredAirlines: [] as string[],
  IsPinned: false,
};

export const DEFAULT_CONFIG = {
  homeBase: "ATL",
  homeTz: "America/New_York",
  reserveBase: "LAX",
  reserveTz: "America/Los_Angeles",
  // commuteBufferHours: 0,
  // releaseBufferHours: 0,
};

export const TIMEZONES = [
  { label: "Eastern Time", value: "America/New_York" },
  { label: "Central Time", value: "America/Chicago" },
  { label: "Mountain Time", value: "America/Denver" },
  { label: "Pacific Time", value: "America/Los_Angeles" },
  { label: "Hawaii Time", value: "Pacific/Honolulu" },
  { label: "UTC", value: "UTC" },
];

export const AIRLINES = [
  { "code": "02Q", "name": "Titan Airways" },
  { "code": "04Q", "name": "Tradewind Aviation" },
  { "code": "06Q", "name": "Master Top Linhas Aereas Ltd." },
  { "code": "07Q", "name": "Flair Airlines Ltd." },
  { "code": "09Q", "name": "Swift Air, LLC d/b/a Eastern Air Lines d/b/a Eastern" },
  { "code": "0BQ", "name": "DCA" },
  { "code": "0CQ", "name": "ACM AIR CHARTER GmbH" },
  { "code": "0FQ", "name": "Maine Aviation Aircraft Charter, LLC" },
  { "code": "0HQ", "name": "Polar Airlines de Mexico d/b/a Nova Air" },
  { "code": "0J", "name": "JetClub AG" },
  { "code": "0LQ", "name": "Metropix UK, LLP." },
  { "code": "0Q", "name": "Flying Service N.V." },
  { "code": "0QQ", "name": "TAG Aviation (UK) Ltd." },
  { "code": "0RQ", "name": "TAG Aviation Espana S.L." },
  { "code": "0UQ", "name": "Comlux Malta, Ltd." },
  { "code": "0VQ", "name": "Ocean Sky (UK) Limited" },
  { "code": "0YQ", "name": "Comlux Malta Ltd." },
  { "code": "10Q", "name": "Swiss Air Ambulance" },
  { "code": "12Q", "name": "Unijet" },
  { "code": "13Q", "name": "Chartright Air Inc." },
  { "code": "14Q", "name": "London Air Services Limited" },
  { "code": "15Q", "name": "Air Alsie A/S" },
  { "code": "17Q", "name": "Albinati Aeronautics SA" },
  { "code": "1AQ", "name": "Via Airlines d/b/a Sterling Airways" },
  { "code": "1BQ", "name": "Eastern Airlines f/k/a Dynamic Airways, LLC" },
  { "code": "1EQ", "name": "KaiserAir, Inc." },
  { "code": "1HQ", "name": "International Jet Management GmbH" },
  { "code": "1IQ", "name": "Jet link AG" },
  { "code": "1JQ", "name": "Exec Direct Aviation Services Limited" },
  { "code": "1LQ", "name": "Bertelsmann Aviation GmbH" },
  { "code": "1NQ", "name": "JSC The 224th Flight Unit State Airlines" },
  { "code": "1PQ", "name": "Makani Kai Air Charters" },
  { "code": "1QQ", "name": "City Wings Inc dba Seaflight" },
  { "code": "1SQ", "name": "Star Marianas Air Inc." },
  { "code": "1UQ", "name": "Gainjet Aviation SA" },
  { "code": "1WQ", "name": "Ultimate JetCharters LLC dba Ultimate Air Shuttle" },
  { "code": "1XQ", "name": "Dassault Falcon Service" },
  { "code": "1YQ", "name": "Air Charter, Inc d/b/a Air Flamenco" },
  { "code": "1ZQ", "name": "Comlux Aruba NV" },
  { "code": "24Q", "name": "Jet Story" },
  { "code": "25Q", "name": "Mjet GmbH" },
  { "code": "26Q", "name": "Albinati aviation Limited" },
  { "code": "27Q", "name": "Jet Aviation Flight Services, Inc." },
  { "code": "29Q", "name": "Erickson Helicopters" },
  { "code": "2AQ", "name": "ABS JETS A.S" },
  { "code": "2BQ", "name": "Air Medical Ltd." },
  { "code": "2ES", "name": "Smokey Bay Air Inc." },
  { "code": "2EQ", "name": "J&M Alaska Air Tours, Inc. d/b/a Alaska Air Transit" },
  { "code": "2GQ", "name": "Cavok Air LLC" },
  { "code": "2HQ", "name": "Elite Airways LLC" },
  { "code": "2JQ", "name": "Delux Public Charter LLC" },
  { "code": "2KA", "name": "Aerogal" },
  { "code": "2KQ", "name": "Longtail Aviation Ltd." },
  { "code": "2LQ", "name": "Tropic Ocean Airways LLC" },
  { "code": "2NQ", "name": "LIMA NY Corp d/b/a Fly The Whale" },
  { "code": "2O", "name": "Island Air Service" },
  { "code": "2OQ", "name": "Talofa Airways Limited" },
  { "code": "2PA", "name": "Air Philippines Corp d/b/a Airphil Express, Philippines Airlines" },
  { "code": "2PQ", "name": "21 Air LLC" },
  { "code": "2RQ", "name": "Luxaviation S A" },
  { "code": "2TQ", "name": "Trans Northern Airways d/b/a Air Unlimited Charter Services" },
  { "code": "2UQ", "name": "Svenskt Industriflyg AB" },
  { "code": "34Q", "name": "Polaris Aviation Solutions, LLC" },
  { "code": "35Q", "name": "Aztec Worldwide Airlines, Inc. d/b/a Aztec Airways" },
  { "code": "36Q", "name": "Air Hamburg Luftverkehrsgesellschaft mbH" },
  { "code": "37", "name": "Zeal 320" },
  { "code": "37Q", "name": "Hillwood Airways, LLC f/k/a ATX Air Services, LLC" },
  { "code": "38Q", "name": "Key Lime Air Corporation" },
  { "code": "3AA", "name": "Airgate Aviation, Inc." },
  { "code": "3AQ", "name": "Maritime Helicopters, Inc." },
  { "code": "3BQ", "name": "Nealco Air Charter Services, Inc. d/b/a Watermakers Air" },
  { "code": "3CQ", "name": "Andrew Airways, Inc." },
  { "code": "3EM", "name": "Multi-Aero, Inc. d/b/a Air Choice One" },
  { "code": "3EQ", "name": "Scott Aviation, LLC d/b/a Silver Air" },
  { "code": "3FQ", "name": "Western Air Charter, Inc. d/b/a Jet Edge" },
  { "code": "3KQ", "name": "Junipogo, LLC" },
  { "code": "3MS", "name": "Silver Airways" },
  { "code": "3SA", "name": "AeroLogic GmbH" },
  { "code": "3SD", "name": "Compagnie Aerienne Inter Regionale Express dba Air Antilles Express & Air Guyane" },
  { "code": "3U", "name": "Sichuan Airlines Co Ltd." },
  { "code": "4B", "name": "Boutique Air" },
  { "code": "4C", "name": "Aerovias de Intergracian Regional" },
  { "code": "4M", "name": "LAN Argentina" },
  { "code": "4N", "name": "Air North" },
  { "code": "4O", "name": "ABC Aerolineas SA de CV dba Interjet" },
  { "code": "4S", "name": "Sol Air (Aero Hunduras)" },
  { "code": "4T", "name": "Belair Airlines Ltd." },
  { "code": "4W", "name": "Warbelow" },
  { "code": "4Y", "name": "EUROWINGS DISCOVER GmbH" },
  { "code": "5C", "name": "Challenge Airlines (IL) Ltd." },
  { "code": "5D", "name": "Aerolitoral" },
  { "code": "5J", "name": "Cebu Air Inc d/b/a Cebu Pacific Air" },
  { "code": "5L", "name": "Aerosur" },
  { "code": "5V", "name": "Tatonduk Outfitters Limited d/b/a Everts Air Alaska and Everts Air Cargo" },
  { "code": "5X", "name": "United Parcel Service" },
  { "code": "5Y", "name": "Atlas Air Inc." },
  { "code": "6A", "name": "Aviacsa Airlines" },
  { "code": "6B", "name": "TUIfly Nordic A.B." },
  { "code": "6H", "name": "Israir Airlines" },
  { "code": "6O", "name": "ORBEST AIRLINE" },
  { "code": "6R", "name": "Aerounion Aerotransporte de Carga Union SA de CV" },
  { "code": "6U", "name": "Air Ukraine" },
  { "code": "6Y", "name": "Nicaraguense De Aviacion Sa" },
  { "code": "7B", "name": "Krasair" },
  { "code": "7C", "name": "Jeju Air Co Ltd." },
  { "code": "7H", "name": "Northern Pacific Airways, Inc. Dba Ravn Alaska" },
  { "code": "7I", "name": "Insel Air International B V" },
  { "code": "7L", "name": "Silk Way West Airlines" },
  { "code": "7P", "name": "Apa International Air S.A." },
  { "code": "7S", "name": "Ryan Air f/k/a Arctic Transportation" },
  { "code": "8C", "name": "Air Transport International" },
  { "code": "8E", "name": "Bering Air Inc." },
  { "code": "8I", "name": "Inselair Aruba NV" },
  { "code": "8L", "name": "Servicio Aereo Leo Lopez" },
  { "code": "8R", "name": "Edelweiss Air Ag" },
  { "code": "8V", "name": "Wright Air Service" },
  { "code": "8W", "name": "Fly Airways NV" },
  { "code": "9E", "name": "Endeavor Air Inc." },
  { "code": "9K", "name": "Cape Air" },
  { "code": "9M", "name": "Central Mountain Air" },
  { "code": "9N", "name": "ANA & JP Express Co. Ltd." },
  { "code": "9T", "name": "TravelspanGT, Inc. S.A." },
  { "code": "9V", "name": "Avior Airlines, C.A." },
  { "code": "9W", "name": "Jet Airways (India) Limited" },
  { "code": "9X", "name": "Southern Airways Express, dba Mokulele Airlines" },
  { "code": "A4", "name": "Southern Wind Airlines" },
  { "code": "AA", "name": "American Airlines Inc." },
  { "code": "AAB", "name": "Abelag Aviation AG" },
  { "code": "AAT", "name": "Air Sunshine Inc." },
  { "code": "ABX", "name": "ABX Air Inc" },
  { "code": "AC", "name": "Air Canada" },
  { "code": "AD", "name": "Azul Linhas Aereas Brazileiras S A" },
  { "code": "ADB", "name": "Antonov Company" },
  { "code": "AF", "name": "Compagnie Natl Air France" },
  { "code": "AG", "name": "Arubaanse Luchtvaart Maatschappij NV dba Aruba Airlines" },
  { "code": "AI", "name": "National Aviation Company of India Limited d/b/a Air India" },
  { "code": "ALQ", "name": "Alliance Executive Jets Ltd." },
  { "code": "AM", "name": "Aeromexico" },
  { "code": "AMQ", "name": "Ameristar Air Cargo" },
  { "code": "AN", "name": "ADVANCED AIR, LLC" },
  { "code": "AOQ", "name": "Avon Jet AG" },
  { "code": "AQB", "name": "Scanwings Oy" },
  { "code": "AQQ", "name": "Air Charter (Safa)" },
  { "code": "AR", "name": "Aerolineas Argentinas" },
  { "code": "ARQ", "name": "Flightworx Aviation Ltd" },
  { "code": "AS", "name": "Alaska Airlines Inc." },
  { "code": "AT", "name": "Royal Air Maroc" },
  { "code": "ATQ", "name": "Bairline Fluggesellschaft" },
  { "code": "AV", "name": "Aerovias Nacl De Colombia" },
  { "code": "AVQ", "name": "Aero Laguna S.A. De C.V." },
  { "code": "AX", "name": "Trans States Airlines" },
  { "code": "AY", "name": "Finnair Oy" },
  { "code": "AYQ", "name": "Aerodan S.A. De C.V." },
  { "code": "AZ", "name": "Italia Transporto Aereo S.P.A DBA ITA S.P.A" },
  { "code": "B0", "name": "Dreamjet SAS Dba La Compagnie" },
  { "code": "B6", "name": "JetBlue Airways" },
  { "code": "BA", "name": "British Airways Plc" },
  { "code": "BAQ", "name": "Aero Rentas De Coahuila S.A. De C.V." },
  { "code": "BAS", "name": "Baranautica Air Service LLC" },
  { "code": "BC", "name": "Skymark Airlines Inc." },
  { "code": "BCQ", "name": "Bradley Air Services Ltd." },
  { "code": "BD", "name": "British Midland Airways Ltd." },
  { "code": "BDQ", "name": "Aerotaxis De Aguascalientes S.A. De C.V." },
  { "code": "BE", "name": "Aeroservices Executive" },
  { "code": "BF", "name": "French bee" },
  { "code": "BG", "name": "Biman Bangladesh Airlines" },
  { "code": "BIQ", "name": "Servicios Aeronauticos Z S.A. De C.V." },
  { "code": "BJQ", "name": "Taxirey S.A. De C.V." },
  { "code": "BR", "name": "Eva Airways Corporation" },
  { "code": "BW", "name": "Caribbean Airlines Limited" },
  { "code": "BX", "name": "Air Busan" },
  { "code": "BY", "name": "Britannia Airways Ltd." },
  { "code": "C5", "name": "CommuteAir LLC dba CommuteAir" },
  { "code": "C6", "name": "Canjet Airlines" },
  { "code": "C8", "name": "Cargolux Italia SpA" },
  { "code": "CA", "name": "Air China" },
  { "code": "CAQ", "name": "Challenge Air Luftverkehrs GmbH" },
  { "code": "CAZ", "name": "CAT Aviation" },
  { "code": "CC", "name": "Air Atlanta Icelandic" },
  { "code": "CHQ", "name": "Nomad Aviation AG" },
  { "code": "CI", "name": "China Airlines Ltd." },
  { "code": "CK", "name": "China Cargo Airline" },
  { "code": "CM", "name": "Compania Panamena (Copa)" },
  { "code": "CP", "name": "Alis Cargo Airlines S.P.A." },
  { "code": "CRV", "name": "Acropolis Aviation Ltd." },
  { "code": "CSQ", "name": "Celtic Tech Jet Ltd." },
  { "code": "CT", "name": "Air Atlanta Europe Limited" },
  { "code": "CV", "name": "Cargolux Airlines International S.A" },
  { "code": "CX", "name": "Cathay Pacific Airways Ltd." },
  { "code": "CYQ", "name": "Corse Air International" },
  { "code": "CZ", "name": "China Southern Airlines" },
  { "code": "D7", "name": "Air Asia X Berhad dba Airasia X" },
  { "code": "D8", "name": "Norwegian Air International Ltd." },
  { "code": "DB", "name": "Maleth Aero AOC Ltd." },
  { "code": "DE", "name": "Condor Flugdienst" },
  { "code": "DHQ", "name": "DHL Aero Expresso" },
  { "code": "DI", "name": "Norwegian Air UK Limited" },
  { "code": "DL", "name": "Delta Air Lines Inc." },
  { "code": "DY", "name": "Norwegian Air Shuttle AS" },
  { "code": "E7", "name": "Estafeta Carga Aereas" },
  { "code": "E72", "name": "European Aviation Air Charter" },
  { "code": "E9", "name": "Evelop Airlines SL" },
  { "code": "EAQ", "name": "Executive Airlines, SL" },
  { "code": "EAU", "name": "Elitavia Malta Limited" },
  { "code": "EBW", "name": "AMOS AIR SA" },
  { "code": "EI", "name": "Aer Lingus Plc" },
  { "code": "EK", "name": "Emirates" },
  { "code": "EL", "name": "Ellis Air Taxi Inc." },
  { "code": "ELQ", "name": "Elangeni GmbH" },
  { "code": "EM", "name": "Empire Airlines Inc." },
  { "code": "EQ", "name": "Tame Linea Aerea del Ecuador Tme EP" },
  { "code": "ET", "name": "Ethiopian Airlines" },
  { "code": "EV", "name": "ExpressJet Airlines LLC d/b/a aha!" },
  { "code": "EW", "name": "Eurowings GmbH" },
  { "code": "EY", "name": "Etihad Airways" },
  { "code": "F9", "name": "Frontier Airlines Inc." },
  { "code": "FI", "name": "Icelandair" },
  { "code": "FJ", "name": "Air Pacific Ltd." },
  { "code": "FK", "name": "Flightcraft Air Charter Ltd dba KF Aeroflyer" },
  { "code": "FP", "name": "TAG Aviation S.A." },
  { "code": "FX", "name": "Federal Express Corporation" },
  { "code": "FXQ", "name": "FOX AIRCRAFT, LLC" },
  { "code": "FYQ", "name": "Flying Group Lux S.A." },
  { "code": "G3", "name": "VRG Linhas Aereas S A" },
  { "code": "G4", "name": "Allegiant Air" },
  { "code": "G7", "name": "GoJet Airlines LLC d/b/a United Express" },
  { "code": "GC", "name": "Global Crossing Airlines, Inc." },
  { "code": "GCH", "name": "Grand Canyon Helicopters" },
  { "code": "GCQ", "name": "Glock Aviation GmbH" },
  { "code": "GEQ", "name": "Gestair, S.A." },
  { "code": "GFQ", "name": "Gulf And Caribbean Cargo" },
  { "code": "GJQ", "name": "GainJet Ireland Ltd" },
  { "code": "GQQ", "name": "Executive Express dba Ravn Connect" },
  { "code": "GSQ", "name": "Global Supply System" },
  { "code": "GTQ", "name": "Galistair Trading Ltd" },
  { "code": "GU", "name": "Aviateca, S.A." },
  { "code": "GV", "name": "Grant Aviation" },
  { "code": "GW", "name": "SkyGreece Airlines S A" },
  { "code": "GWQ", "name": "Golden Wings Charter, Ltd" },
  { "code": "H8", "name": "Sky Airline Peru" },
  { "code": "HA", "name": "Hawaiian Airlines Inc." },
  { "code": "HAQ", "name": "Hamilton Jetport Limited" },
  { "code": "HC", "name": "Air Senegal S.A" },
  { "code": "HLQ", "name": "Heavylift Cargo Airlines Lt" },
  { "code": "HU", "name": "Hainan Airlines Company Limited" },
  { "code": "HX", "name": "Hong Kong Airlines Limited" },
  { "code": "HY", "name": "Uzbekistan Airways" },
  { "code": "HYP", "name": "Hyperion Aviation Ltd. dba Hyperion" },
  { "code": "I4", "name": "Scott Air LLC dba Island Air Express" },
  { "code": "IB", "name": "Iberia Air Lines Of Spain" },
  { "code": "IFQ", "name": "FAI rent-a-jet AG" },
  { "code": "IG", "name": "Airitaly S.P.A." },
  { "code": "IGA", "name": "Global Jet Austria, GmbH" },
  { "code": "IWQ", "name": "Island Wings Ltd. Dba Island Wings Charter" },
  { "code": "J2", "name": "Azerbaijan Airlines CJSC" },
  { "code": "J5", "name": "Kalinin Aviation LLC d/b/a Alaska Seaplanes" },
  { "code": "JAG", "name": "JetAlliance Flugbetriebs d/b/a JAF Airservice" },
  { "code": "JB", "name": "Helijet International Inc." },
  { "code": "JCO", "name": "Concierge U Ltd. d/b/a Jet Concierge Club" },
  { "code": "JD", "name": "Beijing Capital Airlines" },
  { "code": "JI", "name": "Jade Cargo International" },
  { "code": "JJ", "name": "Transportes Aeros Meridiona" },
  { "code": "JL", "name": "Japan Air Lines Co. Ltd." },
  { "code": "JQ", "name": "Jetstar Airways Pty Limited" },
  { "code": "JR", "name": "Aero California" },
  { "code": "JRQ", "name": "KENAI AVIATION OPERATIONS, LLC" },
  { "code": "JU", "name": "Air Serbia" },
  { "code": "JVQ", "name": "Prince Aviation" },
  { "code": "JX", "name": "STARLUX AIRLINES" },
  { "code": "K2", "name": "Paklook Air, Inc d/b/a/ Airlift Alaska d/b/a/ Yute Commuter Service" },
  { "code": "K3", "name": "Venture Travel LLC d/b/a Taquan Air Service" },
  { "code": "KA", "name": "Hong Kong Dragonair" },
  { "code": "KA1", "name": "Kenmore Air Express, LLC (subsidiary of Kenmore Air Harbor)" },
  { "code": "KAH", "name": "Kenmore Air Harbor" },
  { "code": "KAQ", "name": "Kalitta Air LLC" },
  { "code": "KAT", "name": "Katmai Air" },
  { "code": "KD", "name": "Western Global" },
  { "code": "KE", "name": "Korean Air Lines Co. Ltd." },
  { "code": "KFQ", "name": "Skyfirst Limited" },
  { "code": "KH", "name": "Aloha Air Cargo" },
  { "code": "KL", "name": "Klm Royal Dutch Airlines" },
  { "code": "KLQ", "name": "Kalitta Charters II" },
  { "code": "KO", "name": "Alaska Central Express" },
  { "code": "KQ", "name": "Kenya Airways PLC" },
  { "code": "KTQ", "name": "Turks Air Ltd." },
  { "code": "KU", "name": "Kuwait Airways Corp." },
  { "code": "KV", "name": "Sky Regional Airlines Inc." },
  { "code": "KX", "name": "Cayman Airways Limited" },
  { "code": "KZ", "name": "Nippon Cargo Airlines" },
  { "code": "L2", "name": "Lynden Air Cargo Airlines" },
  { "code": "L7", "name": "Lan Colombia" },
  { "code": "LA", "name": "Lan-Chile Airlines" },
  { "code": "LC", "name": "Varig Logistica S/A" },
  { "code": "LDM", "name": "Laudamotion GmbH" },
  { "code": "LDQ", "name": "Sparfell Luftfahrt GmbH" },
  { "code": "LF", "name": "CFM Inc d/b/a Contour Airlines d/b/a One Jet Shuttle" },
  { "code": "LH", "name": "Lufthansa German Airlines" },
  { "code": "LJ", "name": "Jin Air Co Ltd." },
  { "code": "LMQ", "name": "Luxaviation EA" },
  { "code": "LO", "name": "Polskie Linie Lotnicze" },
  { "code": "LP", "name": "Lan Peru Airlines" },
  { "code": "LR", "name": "Lacsa" },
  { "code": "LS", "name": "Jet2.com" },
  { "code": "LX", "name": "Swiss International Airlines" },
  { "code": "LXQ", "name": "Luxaviation Germany GmbH" },
  { "code": "LY", "name": "El Al Israel Airlines Ltd." },
  { "code": "M2", "name": "MHS Aviation GmbH" },
  { "code": "M3", "name": "ABSA-Aerolinhas Brasileiras" },
  { "code": "M6", "name": "Amerijet International" },
  { "code": "M7", "name": "Aerotransportes Mas De Crga" },
  { "code": "MA", "name": "Malev Hungarian Airlines" },
  { "code": "MF", "name": "Xiamen Airlines Co., Ltd." },
  { "code": "MH", "name": "Malaysian Airline System" },
  { "code": "MOQ", "name": "Morningstar Air Express" },
  { "code": "MP", "name": "Martinair Holland N.V." },
  { "code": "MQ", "name": "Envoy Air" },
  { "code": "MS", "name": "Egyptair" },
  { "code": "MT", "name": "Thomas Cook Airlines Uk Ltd." },
  { "code": "MU", "name": "China Eastern Airlines" },
  { "code": "MX", "name": "Breeze Aviation Group DBA Breeze" },
  { "code": "N0", "name": "Norse Atlantic Airways,AS" },
  { "code": "N3", "name": "Vuela EL Salvador S.A. de C.V." },
  { "code": "N6", "name": "Aero Continente" },
  { "code": "N8", "name": "National Air Cargo Group Inc d/ba National Airlines" },
  { "code": "NC", "name": "Northern Air Cargo Inc." },
  { "code": "NEW", "name": "New England Airlines Inc." },
  { "code": "NH", "name": "All Nippon Airways Co." },
  { "code": "NIQ", "name": "AVCON JET MALTA LTD" },
  { "code": "NJE", "name": "NetJets Transportes Aereos, S.A." },
  { "code": "NJQ", "name": "Romcargo Airline S.R.L" },
  { "code": "NK", "name": "Spirit Air Lines" },
  { "code": "NLQ", "name": "Nolinor Aviation" },
  { "code": "NOS", "name": "Neos S.P.A" },
  { "code": "NQ", "name": "Air Japan Co" },
  { "code": "NWQ", "name": "N. W. Territorial Airways" },
  { "code": "NZ", "name": "Air New Zealand" },
  { "code": "O6", "name": "Oceanair Linhas Aereas S A" },
  { "code": "OF", "name": "Air Finland Ltd." },
  { "code": "OG", "name": "Fly PLAY ehf" },
  { "code": "OH", "name": "PSA Airlines Inc." },
  { "code": "OJ", "name": "Fly Jamaica Airways Limited" },
  { "code": "OK", "name": "Czech Airlines" },
  { "code": "OO", "name": "SkyWest Airlines Inc." },
  { "code": "OR", "name": "TUI Airlines Nederland B.V." },
  { "code": "OS", "name": "Austrian Airlines" },
  { "code": "OZ", "name": "Asiana Airlines Inc." },
  { "code": "P3", "name": "Cargologicair Limited" },
  { "code": "PAF", "name": "Pathfinder Aviation" },
  { "code": "PBQ", "name": "Privatair" },
  { "code": "PD", "name": "Porter Airlines, Inc." },
  { "code": "PEQ", "name": "SkyLink Express Inc." },
  { "code": "PF", "name": "Primera Air Scandinavia" },
  { "code": "PFQ", "name": "Asia Pacific" },
  { "code": "PH", "name": "Polynesian Airlines Ltd." },
  { "code": "PK", "name": "Pakistan International Airlines" },
  { "code": "PO", "name": "Polar Air Cargo Airways" },
  { "code": "POQ", "name": "Polyot Airlines" },
  { "code": "PP", "name": "Jet Aviation Business Jets AG" },
  { "code": "PPQ", "name": "Propair" },
  { "code": "PR", "name": "Philippine Airlines Inc." },
  { "code": "PS", "name": "Ukraine International Airlines" },
  { "code": "PT", "name": "Piedmont Airlines" },
  { "code": "PTQ", "name": "Pontair Ltd." },
  { "code": "PY", "name": "Surinam Airways Limited" },
  { "code": "Q5", "name": "40-Mile Air" },
  { "code": "Q6", "name": "Vuela Aviacion, S.A." },
  { "code": "Q7", "name": "SkyBahamas Airlines Ltd." },
  { "code": "QF", "name": "Qantas Airways Ltd." },
  { "code": "QFX", "name": "Sparfell Malta Ltd" },
  { "code": "QK", "name": "Jazz Aviation LP" },
  { "code": "QO", "name": "Aeromexpress" },
  { "code": "QR", "name": "Qatar Airways (Q.C.S.C)" },
  { "code": "QS", "name": "Travel Service, a.s. d/b/a SmartWings" },
  { "code": "QT", "name": "Transportes Aereos Mercantiles Panamericanos S.A" },
  { "code": "QX", "name": "Horizon Air" },
  { "code": "QY", "name": "European Air Transport Leipzig GmbH" },
  { "code": "R0", "name": "Tantalus Air Ltd. d/b/a Harbour Air d/b/a Harbour Air Seaplanes" },
  { "code": "R2", "name": "Orenburg Airlines" },
  { "code": "R3", "name": "Air Company Yakutia" },
  { "code": "RC", "name": "P/F Atlantic Airways" },
  { "code": "RG", "name": "Varig S. A." },
  { "code": "RJ", "name": "Alia-(The) Royal Jordanian" },
  { "code": "RO", "name": "Tarom Romanian Air Transpor" },
  { "code": "RU", "name": "AirBridgeCargo Airlines Limited" },
  { "code": "RV", "name": "Air Canada rouge LP" },
  { "code": "RVQ", "name": "Reeve Air Alaska, LLC" },
  { "code": "S3", "name": "Santa Barbara Airlines, C.A" },
  { "code": "S4", "name": "Sata Internacional" },
  { "code": "S6", "name": "Star Air A/S" },
  { "code": "SA", "name": "South African Airways" },
  { "code": "SE", "name": "XL Airways France" },
  { "code": "SEB", "name": "Seaborne Virgin Islands, Inc." },
  { "code": "SI", "name": "Sierra Pacific Airlines" },
  { "code": "SK", "name": "Scandinavian Airlines Sys." },
  { "code": "SN", "name": "Brussels Airlines N.V." },
  { "code": "SNK", "name": "Spernak Airways Inc." },
  { "code": "SQ", "name": "Singapore Airlines Ltd." },
  { "code": "SU", "name": "Aeroflot Russian Airlines" },
  { "code": "SV", "name": "Saudi Arabian Airlines Corp" },
  { "code": "SVW", "name": "Global Jet Luxembourg, Sa" },
  { "code": "SWQ", "name": "Swiss Private Jet S.A." },
  { "code": "SY", "name": "Sun Country Airlines d/b/a MN Airlines" },
  { "code": "TA", "name": "Taca International Airlines" },
  { "code": "TB", "name": "TUI Airlines Belgium N.V. d/b/a Jetairfly" },
  { "code": "TBQ", "name": "Triair Bermuda Flt Operations" },
  { "code": "TEQ", "name": "TAG Aviation (Malta) Ltd." },
  { "code": "TG", "name": "Thai Airways International Ltd." },
  { "code": "TH", "name": "Transmile Air Service" },
  { "code": "TIQ", "name": "Tyrolean Jet Service" },
  { "code": "TK", "name": "Turk Hava Yollari A.O." },
  { "code": "TN", "name": "Air Tahiti Nui" },
  { "code": "TP", "name": "Tap-Portuguese Airlines" },
  { "code": "TQ", "name": "Tailwind Air, LLC" },
  { "code": "TQQ", "name": "Taca Peru" },
  { "code": "TR", "name": "Scoot Tigerair Pte Ltd d/b/a Scoot" },
  { "code": "TRA", "name": "Aeromexico Travel" },
  { "code": "TS", "name": "Air Transat" },
  { "code": "TZQ", "name": "First Choice Airways" },
  { "code": "U7", "name": "USA Jet Airlines Inc." },
  { "code": "UA", "name": "United Air Lines Inc." },
  { "code": "UO", "name": "Hong Kong Express Airways Limited" },
  { "code": "UP", "name": "Bahamasair Holding Limited" },
  { "code": "UX", "name": "Air Europa" },
  { "code": "V4", "name": "Vensecar International" },
  { "code": "V6", "name": "CLAIRMONT HOLDINGS d/b/a VI AIRLINK" },
  { "code": "V8", "name": "Iliamna Air Taxi" },
  { "code": "VA", "name": "Virgin Blue International Airlines t/a V Australia" },
  { "code": "VB", "name": "Aeroenlaces Nacionales, S.A. de C.V. d/b/a VivaAerobus" },
  { "code": "VH", "name": "Fast Colombia SAS d/b/a Viva Colombia" },
  { "code": "VI", "name": "Vieques Air Link Inc." },
  { "code": "VIQ", "name": "Volga-Dnepr Airlines" },
  { "code": "VJT", "name": "VistaJet Limited" },
  { "code": "VN", "name": "Vietnam Airline" },
  { "code": "VR", "name": "Transportes Aereos De Cabo" },
  { "code": "VS", "name": "Virgin Atlantic Airways" },
  { "code": "VSA", "name": "VistaJet Luftfahrtunternehmen GmbH" },
  { "code": "VV", "name": "Aerosvit Ukranian Airlines" },
  { "code": "VW", "name": "Transportes Aeromar S.A de C.V" },
  { "code": "W3", "name": "Arik Air International" },
  { "code": "W8", "name": "Cargojet Airways Ltd." },
  { "code": "WAP", "name": "Arrow Panama" },
  { "code": "WEQ", "name": "Aero-Services-Corporate" },
  { "code": "WFL", "name": "World2Fly SLU" },
  { "code": "WG", "name": "Sunwing Airlines Inc." },
  { "code": "WGT", "name": "Volkswagen AirSevice GmbH dba Volkswagon" },
  { "code": "WI", "name": "Sky Lease Cargo" },
  { "code": "WL", "name": "Caribbean Sun Airlines, Inc. d/b/a World Atlantic Airlines" },
  { "code": "WN", "name": "Southwest Airlines Co." },
  { "code": "WO", "name": "SWOOP Inc." },
  { "code": "WPT", "name": "World2Fly Portugal SA" },
  { "code": "WR", "name": "WestJet Encore Ltd." },
  { "code": "WRD", "name": "Ward Air" },
  { "code": "WS", "name": "Westjet" },
  { "code": "WST", "name": "Friday Harbor Seaplanes" },
  { "code": "WW", "name": "WOW Air ehf" },
  { "code": "X4", "name": "Air Excursions LLC" },
  { "code": "X6", "name": "Challenge Air Cargo, Ltd" },
  { "code": "X7", "name": "Challenge Airlines (BE) S.A." },
  { "code": "X9", "name": "Omni Air International LLC" },
  { "code": "XL", "name": "Lan Ecuador" },
  { "code": "XP", "name": "TEM Enterprises dba Avelo Airlines" },
  { "code": "Y2", "name": "Globespan Airways Limited d/b/a Flyglobespan" },
  { "code": "Y4", "name": "Concesionaria Vuela Compania De Aviacion SA de CV (Volaris)" },
  { "code": "Y7", "name": "Flyjet Limited d/b/a Silverjet" },
  { "code": "Y8", "name": "Yangtze River Express Airlines Company" },
  { "code": "Y9", "name": "1263343 Alberta Inc. d/b/a Lynx Air" },
  { "code": "YB", "name": "HARBOUR AIR LTD. D/B/A HARBOUR AIR SEAPLANES, WHISTLER AIR AND SALTSPRING AIR" },
  { "code": "YR", "name": "Grand Canyon Airlines, Inc. d/b/a Grand Canyon Airlines d/b/a Scenic Airlines" },
  { "code": "YV", "name": "Mesa Airlines Inc." },
  { "code": "YX", "name": "Republic Airline" },
  { "code": "Z0", "name": "Norse Atlantic UK Ltd" },
  { "code": "Z3", "name": "Bidzy Ta Hot Aana, Inc. d/b/a Tanana Air Service" },
  { "code": "Z3Q", "name": "PM Air, LLC" },
  { "code": "ZB", "name": "Monarch Airlines" },
  { "code": "ZE", "name": "Eastar Jet Co Ltd." },
  { "code": "ZF", "name": "AZUR Air LLC" },
  { "code": "ZG", "name": "ZIPAIR Tokyo Inc." },
  { "code": "ZK", "name": "Great Lakes Airlines" },
  { "code": "ZP", "name": "Silk Way Airlines, LLC" },
  { "code": "ZW", "name": "Air Wisconsin Airlines Corp" },
  { "code": "ZX", "name": "Air Georgian" }
]

